// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWp4wNcuGnuc6cUKvg3KBSbmcmOuogmNI',
    appId: '1:933661572754:web:YOUR_WEB_APP_ID',
    messagingSenderId: '933661572754',
    projectId: 'runwithme-eb52d',
    authDomain: 'runwithme-eb52d.firebaseapp.com',
    storageBucket: 'runwithme-eb52d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWp4wNcuGnuc6cUKvg3KBSbmcmOuogmNI',
    appId: '1:933661572754:android:6ac4e41674ea00e4f7704b',
    messagingSenderId: '933661572754',
    projectId: 'runwithme-eb52d',
    storageBucket: 'runwithme-eb52d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAsVrCpsT46QiaHW2itLu5h-C_RSsMY1I',
    appId: '1:933661572754:ios:6fd9b4145ba7b61bf7704b',
    messagingSenderId: '933661572754',
    projectId: 'runwithme-eb52d',
    storageBucket: 'runwithme-eb52d.firebasestorage.app',
    iosBundleId: 'com.idil.runwithmeApp',
  );
}
